#!/bin/sh 

TG=test_su2
OBJ=$TG.out
WD=$TG
DIR_DATA=8x8a

if test ! -d $WD
then
	mkdir $WD
fi

cp $OBJ $WD

cd $WD
mkdir $DIR_DATA

nice -20 $OBJ << EOF
4.0d0 5
1 11837415 50
EOF

rm $OBJ

mv data.$TG $DIR_DATA

exit 0














